apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svcmonitor-backend
  namespace: quiz
  labels:
    app: deploy
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - quiz
  selector:
    matchLabels:
      app: backend